// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNikS4akqvtGLRySSJu3FagzbF85nH4DY',
    appId: '1:698403316332:web:81e351129aa235955bae49',
    messagingSenderId: '698403316332',
    projectId: 'culinary-craft',
    authDomain: 'culinary-craft.firebaseapp.com',
    storageBucket: 'culinary-craft.appspot.com',
    measurementId: 'G-WG6ZGEXRTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjzKV5GRZ-tEAGGjk-Ko822Y3bv388JNk',
    appId: '1:698403316332:android:09418ec8a306b41f5bae49',
    messagingSenderId: '698403316332',
    projectId: 'culinary-craft',
    storageBucket: 'culinary-craft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUcjObOWgQKiUPTMsAlFf2HFiJxP19Ww8',
    appId: '1:698403316332:ios:ddd19cac5acdc0d25bae49',
    messagingSenderId: '698403316332',
    projectId: 'culinary-craft',
    storageBucket: 'culinary-craft.appspot.com',
    iosClientId: '698403316332-7t6tqmhss6jno4pjfksonib0m8kdnttb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUcjObOWgQKiUPTMsAlFf2HFiJxP19Ww8',
    appId: '1:698403316332:ios:c1c21184936376d55bae49',
    messagingSenderId: '698403316332',
    projectId: 'culinary-craft',
    storageBucket: 'culinary-craft.appspot.com',
    iosClientId: '698403316332-ur9ol1dtnvr5gkhmqrobpg3fr312ikgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fud.RunnerTests',
  );
}
